
hydra:
  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'
      detailed:
        format: '%(levelname)s - %(asctime)s - %(name)s - %(message)s'
    handlers:
      console:
        class: rich.logging.RichHandler
        formatter: simple
        level: INFO
        markup: true
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: detailed
        filename: ${hydra.runtime.output_dir}/main.log
        maxBytes: 10485760
        backupCount: 5
        level: DEBUG
    root:
      level: DEBUG
      handlers: [console, file]

